### ISSUE TITLE
install on windows

### ISSUE THREAD

**Issue by ZaytsevArtem** [adeel/srt-shift#6]
First of all i thank the author for the script, it works just fine, saved my time.

I had some problems with installing the script on windows & i decided to describe the workaround here in hope it helps same lamers as me.

1. The author didn't mention that python 2 version should be used to run the script. I don't know if py 3 was supposed to be supported but it wasn't for me. I have both 2 & 3 py versions installed so i had to use py «-2» option.

2. The author didn't mention that ez_setup should be installed first. Not a big deal but a short line in readme could save some time:
py -2 -m pip install ez_setup

3. pip doesn't want to install the script because since some time it doesn't allow unsafe simple http urls (https only). btw if the author is still alive, he could fix it i guess. Maybe i also could but i don't wanna touch the working code as i'm not so deep into py. The workaround here for me was to use easy_install:
py -2 -m easy_install srt-shift
If it can't recognize the srt-shift by itself (somehow I had this problem), u can try to specify the github archive location:
py -2 -m easy_install https://github.com/adeel/srt-shift/archive/master.zip

4. And at the finish line the script running also wasn't too simple. I also had to use the py version prefix as i mentioned before plus py peremptorily didn't want to find the installed srt-shift module despite pip showed it by the -list option. It was only luck that I discovered to use the underscore instead of dash:
py -2 -m srt_shift in.srt 5 > out.srt

**Comment by adeel** [comment]
Thanks!  When the script was written, pip and python 3 were not around yet.  I should update it but I don't know when I'll get around to it.

**Comment by adeel** [comment]
Also, this exists now and is much better: https://github.com/smacke/subsync
